Create VIEW CourseOfferingsLastYear AS
    SELECT COURSE.COURSE_NAME,COURSE.COURSE_ID,COURSE.COURSE_DURATION,COURSE.COURSE_COST,OFFERING.OFFERING_ID,OFFERING.STARTDATE,OFFERING.OFFERING_LOCATION,OFFERING.INSTRUCTOR FROM COURSE
    INNER JOIN OFFERING ON OFFERING.COURSE_ID = COURSE.COURSE_ID
    WHERE OFFERING.STARTDATE >= (SYSDATE - 365)
    ORDER BY OFFERING.STARTDATE;

-- VIEW CourseOfferingsLastYear;